apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "sswebsites.crds.cloudnative.mx"
spec:
  group: "crds.cloudnative.mx"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "sswebsites"
    singular: "sswebsite"
    kind: "SimpleWebsiteConfig"
    shortNames: ['sws']
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["name","email","domain"]
          properties:
            name:
              type: "string"
              minimum: 1
            email:
              type: "string"
              minimum: 1
            domain:
              type: "string"
              minimum: 1  
