// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/crds/v1alpha1.SimpleWebsiteConfig":       schema_pkg_apis_crds_v1alpha1_SimpleWebsiteConfig(ref),
		"./pkg/apis/crds/v1alpha1.SimpleWebsiteConfigSpec":   schema_pkg_apis_crds_v1alpha1_SimpleWebsiteConfigSpec(ref),
		"./pkg/apis/crds/v1alpha1.SimpleWebsiteConfigStatus": schema_pkg_apis_crds_v1alpha1_SimpleWebsiteConfigStatus(ref),
	}
}

func schema_pkg_apis_crds_v1alpha1_SimpleWebsiteConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SimpleWebsiteConfig is the Schema for the simplewebsiteconfigs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/crds/v1alpha1.SimpleWebsiteConfigSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/crds/v1alpha1.SimpleWebsiteConfigStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/crds/v1alpha1.SimpleWebsiteConfigSpec", "./pkg/apis/crds/v1alpha1.SimpleWebsiteConfigStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_crds_v1alpha1_SimpleWebsiteConfigSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SimpleWebsiteConfigSpec defines the desired state of SimpleWebsiteConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_crds_v1alpha1_SimpleWebsiteConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SimpleWebsiteConfigStatus defines the observed state of SimpleWebsiteConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
