// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleWebsiteConfig) DeepCopyInto(out *SimpleWebsiteConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleWebsiteConfig.
func (in *SimpleWebsiteConfig) DeepCopy() *SimpleWebsiteConfig {
	if in == nil {
		return nil
	}
	out := new(SimpleWebsiteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimpleWebsiteConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleWebsiteConfigList) DeepCopyInto(out *SimpleWebsiteConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SimpleWebsiteConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleWebsiteConfigList.
func (in *SimpleWebsiteConfigList) DeepCopy() *SimpleWebsiteConfigList {
	if in == nil {
		return nil
	}
	out := new(SimpleWebsiteConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimpleWebsiteConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleWebsiteConfigSpec) DeepCopyInto(out *SimpleWebsiteConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleWebsiteConfigSpec.
func (in *SimpleWebsiteConfigSpec) DeepCopy() *SimpleWebsiteConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SimpleWebsiteConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleWebsiteConfigStatus) DeepCopyInto(out *SimpleWebsiteConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleWebsiteConfigStatus.
func (in *SimpleWebsiteConfigStatus) DeepCopy() *SimpleWebsiteConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SimpleWebsiteConfigStatus)
	in.DeepCopyInto(out)
	return out
}
