apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: simplewebsiteconfigs.crds.cloudnative.mx
spec:
  group: crds.cloudnative.mx
  names:
    kind: SimpleWebsiteConfig
    listKind: SimpleWebsiteConfigList
    plural: simplewebsiteconfigs
    singular: simplewebsiteconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          required: ["name","email","domain"]
          properties:
            name:
              type: "string"
              minimum: 1
            email:
              type: "string"
              minimum: 1
            domain:
              type: "string"
              minimum: 1
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
